#prebared by Abdelrhman Ellawendi
CC= gcc
INCS= -w .\Application\application.c .\Data_Bases\File_Handling\file_handling.c .\Data_Structures\List\list.c .\Data_Structures\Stack\Stack.c .\Payment_System\Card\card.c .\Payment_System\Server\server.c .\Payment_System\Terminal\terminal.c 
project_name= Payment_Application
all: $(project_name).exe
$(project_name).exe:  
	$(CC) $(INCS) -o $@ 
clean:
	rm  *.exe
	@echo "Everything clean"

